<template>
  <modal name="word-modal"
         v-bind:adaptive="adaptive"
         v-bind:resizable="resizable"
         v-bind:draggable="draggable"
         v-bind:scrollable="scrollable"
         v-bind:reset="reset"
         v-bind:minWidth="minWidth"
         v-bind:minHeight="minHeight"
         @before-open="beforeOpen"
         @before-close="beforeClose">
  <v-container grid-list-md text-xs-center>
     <v-layout v-bind="binding">
          <!-- Modal Header -->
          <v-flex>
            <h2>Word</h2>
          </v-flex>

          <!-- Modal body -->
          <v-flex>
            <v-container grid-list-md>
                         <v-text-field
                            :rules="[rules.required, rules.min]"
                            v-model="editedItem.word"
                            label="Word">
                         </v-text-field>
                         <v-text-field
                            v-model="editedItem.transcription"
                            label="Transcription">
                         </v-text-field>
                         <v-text-field
                            :rules="[rules.required, rules.min]"
                            v-model="editedItem.translation"
                            label="Translation">
                         </v-text-field>
                         <v-text-field
                            v-model="editedItem.book"
                            label="Book">
                         </v-text-field>
             </v-container>
          </v-flex>

          <!-- Modal footer -->
          <v-flex>
            <v-spacer></v-spacer>
            <v-btn color="blue darken-1" flat @click.native="cancel">Cancel</v-btn>
            <v-btn color="blue darken-1" flat @click.native="save">Save</v-btn>
          </v-flex>
      </v-layout>
    </v-container>
  </modal>
</template>

<script>

export default {
  name: 'WordModal',
  data () {
    return {
      //modal-form params
      adaptive: true,
      resizable: true,
      draggable: true,
      scrollable: false,
      reset: true,
      minHeight: 450,
      minWidth: 400,
      //validation
      rules: {
          required: value => !!value || 'Required.',
          min: v => v.length >= 2 || 'Min 2 characters'
      },
      //params
      mode: null,
      editedItem: {
        _id: '',
        word: '',
        transcription: '',
        translation: '',
        book: '',
        creation_date: Date.now()
      }
    }
  },
  computed: {
      binding () {
        const binding = {}

        if (this.$vuetify.breakpoint.mdAndUp) binding.column = true

        return binding
      }
  },
  methods: {
    cancel () {
      this.$modal.hide('word-modal');
    },
    save (e) {

        let hide = this.$modal.hide.bind(this.$modal);
        let mutation = this.mode === "create" ? 'createWord' : 'editWord';
      
        let payload = {
            data: this.editedItem,
            callback: (res, commit) => {
              if (res.status === 200) {
                hide('word-modal');
                //when creating a new item we need _id generated by mongodb to add this item properly
                //to the state. In edititng mode this.editedItem already contains valid _id
                commit(mutation, this.mode === "create" ? res.data : this.editedItem);
              }
           }
        }

        if (this.mode === "create") {
             if (this.editedItem.hasOwnProperty('_id')) delete this.editedItem._id;
             this.$store.dispatch('words/createWord', payload);
        }
        else { //edit mode
             this.$store.dispatch('words/editWord', payload);
        }

    },
    beforeOpen (event) {
      this.mode = event.params.mode;
      if (this.mode === "edit") {
         let itm = event.params.item;
         this.editedItem = Object.assign({}, itm);
      }
      else {
        this.editedItem.word = '';
        this.editedItem.transcription = '',
        this.editedItem.translation = '',
        this.editedItem.book = '',
        this.editedItem.creation_date = Date.now();
      }
    },
    beforeClose (event) {
      //console.log(event)
      // If modal was open less then 5000 ms - prevent closing it
      //if (this.time + this.duration < Date.now()) {
        //event.stop()
      //}
    }
  }
}
</script>
